import React from 'react';
import { Text, View, StyleSheet, Pressable, TextInput, useWindowDimensions } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useAppTheme } from '../store/theme';

export const purple = '#5B4DF0';
const webInputReset = { outlineStyle: 'none', boxShadow: 'none', backgroundColor: 'transparent' } as any;
const clamp = (value: number, min: number, max: number) => Math.min(Math.max(value, min), max);
const brandFontThemes = {
  clean: { fontFamily: 'System', fontWeight: '900' },
  rounded: { fontFamily: 'Avenir Next', fontWeight: '900' },
  editorial: { fontFamily: 'Georgia', fontWeight: '700' },
  modern: { fontFamily: 'Futura', fontWeight: '800' },
} as const;
const activeBrandFont = brandFontThemes.modern;
export function Header({title,sub,plus,searchValue='',onSearchChange,onSearchSubmit,onSearchCancel}:{title:string;sub:string;plus?:()=>void;searchValue?:string;onSearchChange?:(value:string)=>void;onSearchSubmit?:()=>void;onSearchCancel?:()=>void}){const {width,height}=useWindowDimensions();const {colors}=useAppTheme();const compactScale=clamp(Math.min(width/390,height/844),.56,1.08);const searching=!!searchValue.trim()&&!!onSearchCancel;const searchHeight=clamp(width*.15*compactScale,40,74);const searchFont=clamp(width*.04*compactScale,12,20);const searchSizing={height:searchHeight,borderRadius:clamp(searchHeight*.28,12,22),paddingHorizontal:clamp(width*.04*compactScale,10,22),gap:clamp(width*.025*compactScale,7,15)};const searchInputSizing={height:searchHeight-8,fontSize:searchFont,lineHeight:searchFont+4};const searchIconSize=clamp(width*.055*compactScale,16,25);const headerSizing={paddingTop:clamp(height*.06,28,52),paddingHorizontal:clamp(width*.07,20,28),paddingBottom:clamp(height*.028,14,30),borderBottomLeftRadius:clamp(width*.08,22,32),borderBottomRightRadius:clamp(width*.08,22,32)};const titleSizing={fontSize:clamp(width*.118*compactScale,28,46),lineHeight:clamp(width*.133*compactScale,32,52)};const subSizing={fontSize:clamp(width*.047*compactScale,12,18),lineHeight:clamp(width*.059*compactScale,16,23)};const circleSize=clamp(width*.155*compactScale,40,62);const circleSizing={right:headerSizing.paddingHorizontal,top:clamp(height*.055,24,48),width:circleSize,height:circleSize,borderRadius:circleSize/2};const circleIconSize=clamp(circleSize*.55,22,34);return <View style={[s.header,headerSizing,{backgroundColor:colors.primary}]}><View><Text style={[s.h1, activeBrandFont,titleSizing]}>{title}</Text><Text style={[s.sub,subSizing]}>{sub}</Text></View>{searching?<Pressable onPress={onSearchCancel} style={[s.circle,circleSizing]}><Ionicons name="close" size={circleIconSize} color="white"/></Pressable>:plus&&<Pressable onPress={plus} style={[s.circle,circleSizing]}><Ionicons name="add" size={circleIconSize} color="white"/></Pressable>}<View style={[s.search,searchSizing,{marginTop:clamp(height*.026,12,30)}]}><Ionicons name="search" size={searchIconSize} color="#D7D1FF"/><TextInput value={searchValue} onChangeText={onSearchChange} onSubmitEditing={onSearchSubmit} returnKeyType="search" placeholder="Search your products or brands" placeholderTextColor="#C8C0FF" selectionColor="white" underlineColorAndroid="transparent" style={[s.searchInput,searchInputSizing,webInputReset]}/></View></View>}
export function Pill({text}:{text:string}){const {width,height}=useWindowDimensions();const compactScale=clamp(Math.min(width/390,height/844),.56,1.08);let bg=text==='Active'?'#DDFBE8':text==='Expired'?'#FFE0E0':'#FFF1C9';let c=text==='Active'?'#17713A':text==='Expired'?'#A31212':'#9A4D00';const pillSizing={paddingHorizontal:clamp(width*.046*compactScale,10,18),paddingVertical:clamp(width*.02*compactScale,5,8),borderRadius:clamp(width*.056*compactScale,14,22),fontSize:clamp(width*.046*compactScale,12,18),lineHeight:clamp(width*.058*compactScale,15,22)};return <Text style={[s.pill,pillSizing,{backgroundColor:bg,color:c}]}>{text}</Text>}
export function Section({icon,title}:{icon:string;title:string}){return <View style={s.sectionTitle}><Ionicons name={icon as any} size={24} color={purple}/><Text style={s.sectionText}>{title}</Text></View>}
const s=StyleSheet.create({header:{backgroundColor:purple},h1:{color:'white'},sub:{color:'#D7D1FF',fontWeight:'500'},circle:{position:'absolute',alignItems:'center',justifyContent:'center',backgroundColor:'rgba(255,255,255,.18)',borderWidth:1,borderColor:'rgba(255,255,255,.35)'},search:{borderWidth:1.4,borderColor:'rgba(255,255,255,.28)',backgroundColor:'rgba(255,255,255,.14)',flexDirection:'row',alignItems:'center'},searchInput:{flex:1,fontWeight:'700',color:'white',paddingVertical:0,borderWidth:0},pill:{fontWeight:'800',overflow:'hidden'},sectionTitle:{flexDirection:'row',alignItems:'center',gap:14,marginTop:28,marginBottom:16},sectionText:{fontSize:26,fontWeight:'800'}});
